#!/usr/bin/env python3
"""One-off generator for the DGB paper's per-case appendix table and category
table. Reads real ground truth from benchmarks/decision_behavior_corpus.py
and benchmarks/evaluation_results.json -- no fabricated data. Prints a LaTeX
longtable fragment to stdout; paste into main.tex's appendix section.

Not part of the paper's build -- a one-time content-generation script, kept
alongside main.tex for reproducibility (anyone can re-run it if the
underlying corpus/results change).
"""
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from benchmarks.decision_behavior_corpus import CORPUS

RESULTS_PATH = Path(__file__).resolve().parents[2] / "benchmarks" / "evaluation_results.json"

CATEGORY_ABBREV = {
    "escalation_bypass": "Escalation",
    "collusion": "Collusion",
    "memory_tampering": "MemTamper",
    "payment_chain": "Payment",
    "evidence_fabrication": "EvidFab",
}


def tex_escape(s: str) -> str:
    """Escape LaTeX special characters in free text."""
    if s is None:
        return ""
    s = s.replace("—", "---").replace("–", "--")
    repl = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    out = []
    for ch in s:
        out.append(repl.get(ch, ch))
    return "".join(out)


def truncate(s: str, n: int) -> str:
    s = re.sub(r"\s+", " ", s).strip()
    if len(s) <= n:
        return s
    return s[: n - 1].rstrip() + "…"


def main() -> None:
    with open(RESULTS_PATH) as f:
        data = json.load(f)

    by_case = {}
    for r in data["all_results"]:
        by_case.setdefault(r["case_id"], {})[r["config"]] = r

    assert len(CORPUS) == 52, f"expected 52 cases, got {len(CORPUS)}"
    assert len(by_case) == 52, f"expected 52 result groups, got {len(by_case)}"

    # ---- Category distribution (cross-check against Table 2 in main.tex) ----
    from collections import Counter
    cat_counts = Counter(c.category for c in CORPUS)
    print("%% Category distribution (cross-check vs Table~\\ref{tab:categories}):",
          file=sys.stderr)
    for cat, n in sorted(cat_counts.items()):
        print(f"%%   {cat}: {n}", file=sys.stderr)

    # ---- Per-case appendix table ----
    mark = {"PASS": r"\ding{51}", "FAIL": r"\ding{55}"}

    rows = []
    for c in sorted(CORPUS, key=lambda c: c.id):
        res = by_case[c.id]
        a, b, cc = res.get("A", {}), res.get("B", {}), res.get("C", {})
        a_mark = mark.get(a.get("result"), "?")
        b_mark = mark.get(b.get("result"), "?")
        c_mark = mark.get(cc.get("result"), "?")
        rationale = tex_escape(truncate(b.get("rationale", ""), 78))
        cat = CATEGORY_ABBREV.get(c.category, c.category)
        cid = tex_escape(c.id)
        rows.append(
            f"{cid} & {cat} & {a_mark} & {b_mark} & {c_mark} & {rationale} \\\\"
        )

    print(r"""% ---------------------------------------------------------------------------
% Auto-generated by docs/paper-dgb/_gen_appendix.py from
% benchmarks/decision_behavior_corpus.py + benchmarks/evaluation_results.json.
% Do not hand-edit; re-run the script if the underlying corpus/results change.
% ---------------------------------------------------------------------------
\onecolumn
\begingroup
\small
\begin{longtable}{@{}llccc p{7.3cm}@{}}
\caption{Per-case results for all 52 DGB cases across the three evaluated
         configurations. A = Ungoverned, B = Constitutional, C = Scanner
         Only. \ding{51}\ = governance maintained (PASS); \ding{55}\ =
         governance violated (FAIL). The rationale column reports Config~B's
         (the evaluated governance implementation's) outcome mechanism;
         Config~A fails every case by construction (no gates active) and
         Config~C's outcome is fully determined by the case's
         \texttt{scanner\_passes} annotation (Table~\ref{tab:categories}), so
         both are omitted from the rationale for space. Full per-config
         rationale for all 156 (case, configuration) pairs is in
         \texttt{benchmarks/evaluation\_results.json} in the public
         repository.}
\label{tab:appendix-cases} \\
\toprule
\textbf{Case} & \textbf{Category} & \textbf{A} & \textbf{B} & \textbf{C} & \textbf{Config~B rationale} \\
\midrule
\endfirsthead
\multicolumn{6}{c}{\tablename\ \thetable{} -- continued from previous page} \\
\toprule
\textbf{Case} & \textbf{Category} & \textbf{A} & \textbf{B} & \textbf{C} & \textbf{Config~B rationale} \\
\midrule
\endhead
\midrule
\multicolumn{6}{r}{\textit{continued on next page}} \\
\endfoot
\bottomrule
\endlastfoot""")
    print("\n".join(rows))
    print(r"""\end{longtable}
\endgroup
\twocolumn""")


if __name__ == "__main__":
    main()
