#!/usr/bin/env python3
"""Generate docs/cve/ from docs/cve/cve-test-mapping.yaml, and check it has not drifted.

    python scripts/generate_cve_pages.py            # write the pages
    python scripts/generate_cve_pages.py --check    # exit 1 on any rule violation or drift

Which CVEs get a page is not decided by hand. `source_citations()` scans
`protocol_tests/` for every CVE identifier and for the test IDs each one is
cited beside, and `validate()` fails unless the mapping accounts for all of
them: every cited CVE is documented or excluded with a reason, and every test
the source pairs with a documented CVE is documented or withheld with a reason.
A documented test that the source does not pair with that CVE fails too, so a
page cannot claim coverage the code does not state.

Two groups of rules, because they need different things:

  HEAD rules      the working tree only. Run everywhere, including the
                  shallow checkout CI uses for the main test job.
  pinned rules    need `pinned_commit` in the object store: every quoted line is
                  checked verbatim against the module at that commit, line
                  anchors are computed there, and the pages are regenerated and
                  compared. In a shallow clone they report that they could not
                  run; the `pinned-provenance` CI job has full history and runs
                  them for real.

Checkout-only: it reads docs/cve/, HARNESS_TEST_CATALOG.md and git history,
none of which the wheel ships. Run from a clone; anywhere else it exits 2 with
one line naming the missing resource.
"""
from __future__ import annotations

import argparse
import ast
import hashlib
import re
import shlex
import subprocess
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    print("PyYAML is required: pip install pyyaml", file=sys.stderr)
    raise SystemExit(2)



def _checkout_root() -> Path:
    """The git checkout this is run from. Not a path climbed from __file__: in an
    installed wheel that is site-packages, which has no docs/ and no history."""
    out = subprocess.run(("git", "rev-parse", "--show-toplevel"), capture_output=True,
                         text=True, check=False)
    top = out.stdout.strip()
    return Path(top) if out.returncode == 0 and top else Path.cwd()


ROOT = _checkout_root()
MAPPING_PARTS = ("docs", "cve", "cve-test-mapping.yaml")


def out_dir(root: Path) -> Path:
    return root / "docs" / "cve"


def mapping_path(root: Path) -> Path:
    return root.joinpath(*MAPPING_PARTS)

CVE_RE = re.compile(r"\bCVE-\d{4}-\d{4,7}\b")
# Same two conventions scripts/validate_owasp_agentic_mapping.py and
# scripts/count_tests.py use for "this module defines that test".
TEST_ID_ASSIGN = re.compile(r'test_id\s*=\s*["\']([A-Z][A-Z0-9]*-\d{3})["\']')
TEST_ID_HELPER = re.compile(r'(?:self\._test_\w+|_test_\w+)\(\s*["\']([A-Z][A-Z0-9]*-\d{3})["\']')
BARE_ID = re.compile(r"\b([A-Z][A-Z0-9]*-\d{3})\b")

OUTCOMES = ("PASS", "FAIL", "INCONCLUSIVE")
OBSERVES = {"target", "local"}
#: Hand-written fields must not carry these. Quotes from the source are exempt:
#: they are the source's words, and checked verbatim instead.
PROHIBITED = ("certified", "certification", "compliant", "compliance",
              "guarantee", "fully mitigates", "is not vulnerable", "is vulnerable",
              "stolen", "best-in-class", "industry-leading")

GENERATED_BANNER = ("<!-- Generated by scripts/generate_cve_pages.py from "
                    "docs/cve/cve-test-mapping.yaml. Do not edit by hand. -->")


# ---------------------------------------------------------------------------
# Derivation from source
# ---------------------------------------------------------------------------

def _norm(text: str) -> str:
    return " ".join(text.split())


def source_citations(root: Path = ROOT) -> tuple[set[str], dict[str, dict[str, set[str]]]]:
    """(every CVE cited in protocol_tests/, {cve: {test_id: {module, ...}}}).

    A CVE and a test ID are paired when both appear in the source of one
    function, which is how every CVE-specific test here states what it covers
    (a `cve=` field, a docstring, or its verdict text).

    Fallback for a family whose tests do not name the CVE themselves: when a
    module's docstring cites a CVE that no function in that module pairs, it is
    paired with the test IDs the module and class docstrings name. That is how
    workspace_trust_harness.py states it. A CVE the docstrings cite only as
    context, with no test ID beside it, pairs with nothing and must be excluded.
    """
    universe: set[str] = set()
    pairs: dict[str, dict[str, set[str]]] = {}

    def add(cve: str, tid: str, rel: str) -> None:
        pairs.setdefault(cve, {}).setdefault(tid, set()).add(rel)

    for path in sorted((root / "protocol_tests").rglob("*.py")):
        text = path.read_text(encoding="utf-8", errors="replace")
        cited = set(CVE_RE.findall(text))
        if not cited:
            continue
        universe |= cited
        rel = str(path.relative_to(root))
        lines = text.splitlines()
        tree = ast.parse(text)
        paired_here: set[str] = set()
        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            seg = "\n".join(lines[node.lineno - 1:node.end_lineno])
            cves = set(CVE_RE.findall(seg))
            tids = set(TEST_ID_ASSIGN.findall(seg))
            for cve in cves:
                for tid in tids:
                    add(cve, tid, rel)
                    paired_here.add(cve)
        docs = ast.get_docstring(tree) or ""
        class_docs = " ".join(ast.get_docstring(n) or "" for n in ast.walk(tree)
                              if isinstance(n, ast.ClassDef))
        defined = set(TEST_ID_ASSIGN.findall(text)) | set(TEST_ID_HELPER.findall(text))
        named = {t for t in BARE_ID.findall(docs + " " + class_docs) if t in defined}
        for cve in set(CVE_RE.findall(docs)) - paired_here:
            for tid in named:
                add(cve, tid, rel)
    return universe, pairs


def defined_test_ids(root: Path = ROOT) -> dict[str, set[str]]:
    """{test_id: {module, ...}} from scripts/count_tests.py, the canonical counter.

    Deriving it separately here would let this guard and the published test
    count disagree about which tests exist.
    """
    sys.path.insert(0, str(root / "scripts"))
    import count_tests  # noqa: E402
    idx: dict[str, set[str]] = {}
    for filename, ids in count_tests.module_ids().items():
        for tid in ids:
            idx.setdefault(tid, set()).add(f"protocol_tests/{filename}")
    return idx


def catalog_entries(root: Path = ROOT) -> dict[str, str]:
    """{test_id: name} from HARNESS_TEST_CATALOG.md rows `ID | Name | path:line`."""
    out: dict[str, str] = {}
    for line in (root / "HARNESS_TEST_CATALOG.md").read_text(encoding="utf-8").splitlines():
        m = re.match(r"^([A-Z][A-Z0-9]*-\d{3}) \| (.+?) \| (\S+)$", line)
        if m:
            out[m.group(1)] = m.group(2)
    return out


def cli_harnesses(root: Path = ROOT) -> dict[str, str]:
    """{harness name: module path} from the HARNESSES registry in cli.py."""
    text = (root / "protocol_tests" / "cli.py").read_text(encoding="utf-8")
    out = {}
    for m in re.finditer(r'^\s{4}"([a-z0-9-]+)":\s*\{\s*\n\s*"module":\s*"([\w.]+)"', text, re.M):
        out[m.group(1)] = m.group(2).replace(".", "/") + ".py"
    return out


# ---------------------------------------------------------------------------
# Git access for the pinned rules
# ---------------------------------------------------------------------------

def _git(root: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(("git", *args), cwd=root, capture_output=True, check=False)


def pin_available(root: Path, sha: str) -> bool:
    return _git(root, "cat-file", "-e", f"{sha}^{{commit}}").returncode == 0


def is_shallow(root: Path) -> bool:
    out = _git(root, "rev-parse", "--is-shallow-repository")
    return out.stdout.decode().strip() == "true"


def pinned_blob(root: Path, sha: str, rel: str) -> bytes | None:
    out = _git(root, "show", f"{sha}:{rel}")
    return out.stdout if out.returncode == 0 else None


def symbol_span(text: str, symbol: str) -> tuple[int, int] | None:
    """(first, last) line of the function named `symbol`, or None."""
    for node in ast.walk(ast.parse(text)):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == symbol:
            return node.lineno, node.end_lineno
    return None


def locate_in(text: str, quote: str, symbol: str | None) -> int | None:
    """Prefer the occurrence inside `symbol`'s own body, so a verdict string is
    anchored to the test that emits it rather than to a comment quoting it."""
    span = symbol_span(text, symbol) if symbol else None
    if span:
        lines = text.splitlines()
        inner = locate("\n".join(lines[span[0] - 1:span[1]]), quote)
        if inner is not None:
            return inner + span[0] - 1
    return locate(text, quote)


def locate(text: str, quote: str) -> int | None:
    """1-based line where `quote` starts in `text`, whitespace-normalised; else None."""
    target = _norm(quote)
    if not target:
        return None
    # Normalised text, with the source line of every normalised character.
    chars: list[str] = []
    where: list[int] = []
    pending_space = False
    for lineno, line in enumerate(text.splitlines(), start=1):
        for ch in line:
            if ch.isspace():
                pending_space = bool(chars)
                continue
            if pending_space:
                chars.append(" ")
                where.append(lineno)
                pending_space = False
            chars.append(ch)
            where.append(lineno)
        pending_space = bool(chars)
    i = "".join(chars).find(target)
    return where[i] if i >= 0 else None


def def_line(text: str, symbol: str) -> int | None:
    m = re.search(r"^[ \t]*def\s+" + re.escape(symbol) + r"\s*\(", text, re.M)
    return text[:m.start()].count("\n") + 1 if m else None


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def _hand_fields(mapping: dict):
    for tid, t in mapping.get("tests", {}).items():
        for key in ("sends",):
            yield f"tests.{tid}.{key}", t.get(key, "")
        for v in t.get("verdicts", []):
            yield f"tests.{tid}.verdicts.{v.get('outcome')}.when", v.get("when", "")
        for n in t.get("notes", []):
            yield f"tests.{tid}.notes", n
    for cve, c in mapping.get("cves", {}).items():
        for d in c.get("documented", []):
            yield f"cves.{cve}.documented.{d.get('test_id')}.why", d.get("why", "")
        for w in c.get("withheld", []):
            yield f"cves.{cve}.withheld.{w.get('test_id')}.reason", w.get("reason", "")
    for cve, e in mapping.get("excluded", {}).items():
        yield f"excluded.{cve}.reason", e.get("reason", "")


def validate(mapping: dict, root: Path = ROOT, *, citations=None, defined=None,
             catalog=None, harnesses=None) -> list[str]:
    """HEAD rules. The keyword arguments exist so a test can inject derived data."""
    fails: list[str] = []

    def fail(rule: str, detail: str) -> None:
        fails.append(f"[{rule}] {detail}")

    universe, pairs = citations if citations is not None else source_citations(root)
    defined = defined if defined is not None else defined_test_ids(root)
    catalog = catalog if catalog is not None else catalog_entries(root)
    harnesses = harnesses if harnesses is not None else cli_harnesses(root)

    cves = mapping.get("cves") or {}
    excluded = mapping.get("excluded") or {}
    tests = mapping.get("tests") or {}

    sha = str(mapping.get("pinned_commit", ""))
    if not re.fullmatch(r"[0-9a-f]{40}", sha):
        fail("pin_format", f"pinned_commit must be a full 40-char SHA, got {sha!r}")
    if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", str(mapping.get("retrieved", ""))):
        fail("retrieved", "retrieved must be an ISO date")

    # r1: every cited CVE is accounted for, once, and nothing stale is listed.
    for cve in sorted(universe):
        if cve not in cves and cve not in excluded:
            fail("r1_unaccounted", f"{cve} is cited in protocol_tests/ but is neither "
                 "documented under `cves` nor listed under `excluded` with a reason")
    for cve in sorted(set(cves) & set(excluded)):
        fail("r1_both", f"{cve} is both documented and excluded")
    for cve in sorted((set(cves) | set(excluded)) - universe):
        fail("r1_stale", f"{cve} is in the mapping but no longer cited in protocol_tests/")
    for cve, e in excluded.items():
        if not (e or {}).get("reason"):
            fail("r1_reason", f"excluded {cve} has no reason")

    # r2: the documented/withheld split covers exactly the source pairs.
    for cve, c in cves.items():
        documented = [d["test_id"] for d in c.get("documented") or []]
        withheld = [w["test_id"] for w in c.get("withheld") or []]
        if not documented:
            fail("r2_empty", f"{cve} documents no test; exclude it instead")
        source_side = set(pairs.get(cve, {}))
        for tid in documented:
            if tid not in source_side:
                fail("r2_unpaired", f"{cve} documents {tid}, but no source in protocol_tests/ "
                     "pairs that test with this CVE")
        for tid in sorted(source_side - set(documented) - set(withheld)):
            fail("r2_unaccounted_pair", f"source pairs {cve} with {tid}; document it or "
                 "withhold it with a reason")
        for tid in sorted(set(documented) & set(withheld)):
            fail("r2_both", f"{cve}/{tid} is both documented and withheld")
        for w in c.get("withheld") or []:
            if not w.get("reason"):
                fail("r2_reason", f"{cve} withholds {w.get('test_id')} with no reason")
        for d in c.get("documented") or []:
            if not d.get("why"):
                fail("r2_why", f"{cve}/{d['test_id']} has no `why`")
            if d["test_id"] not in tests:
                fail("r2_test_entry", f"{cve} documents {d['test_id']}, which has no "
                     "entry under `tests`")
        for key in ("product", "summary", "summary_source", "affected", "fixed", "cvss",
                    "cwe", "published", "cna"):
            if not c.get(key):
                fail("r4_fact", f"{cve} is missing `{key}`")
        if not isinstance(c.get("summary_is_excerpt"), bool):
            fail("r4_fact", f"{cve}: summary_is_excerpt must be true or false")
        if "kev" not in c:
            fail("r4_fact", f"{cve} must state `kev` (null when not listed)")
        if c.get("ghsa") is None and not c.get("ghsa_note"):
            fail("r4_fact", f"{cve} has no GHSA entry and no `ghsa_note` saying so")

    # r3: every test ID exists, in its named module, and in the catalog verbatim.
    used = {d["test_id"] for c in cves.values() for d in c.get("documented") or []}
    for tid in sorted(set(tests) - used):
        fail("r3_orphan", f"tests.{tid} is not documented under any CVE")
    all_ids = used | set(tests) | {w["test_id"] for c in cves.values()
                                   for w in c.get("withheld") or []}
    for tid in sorted(all_ids):
        if tid not in defined:
            fail("r3_defined", f"{tid} is not defined anywhere in protocol_tests/")
        if tid not in catalog:
            fail("r3_catalog", f"{tid} does not appear in HARNESS_TEST_CATALOG.md")
    for tid, t in tests.items():
        mod = t.get("module", "")
        if tid in defined and mod not in defined[tid]:
            fail("r3_module", f"{tid} is not defined in {mod}")
        if not (root / mod).is_file():
            fail("r3_module", f"{tid}: {mod} does not exist")
            continue
        text = (root / mod).read_text(encoding="utf-8", errors="replace")
        if def_line(text, t.get("symbol", "")) is None:
            fail("r3_symbol", f"{tid}: def {t.get('symbol')} not found in {mod}")
        if t.get("observes") not in OBSERVES:
            fail("r3_observes", f"{tid}: observes must be one of {sorted(OBSERVES)}")
        if not t.get("cites"):
            fail("r3_cites", f"{tid} cites no line of its own source")
        outcomes = [v.get("outcome") for v in t.get("verdicts") or []]
        if "PASS" not in outcomes or "FAIL" not in outcomes:
            fail("r3_verdicts", f"{tid} must describe PASS and FAIL")
        for o in outcomes:
            if o not in OUTCOMES:
                fail("r3_verdicts", f"{tid}: unknown outcome {o!r}")

        # r5: the run line names a real harness and only flags it accepts.
        run = t.get("run", "")
        try:
            toks = shlex.split(run)
        except ValueError as e:
            fail("r5_run", f"{tid}: run line does not parse: {e}")
            continue
        if toks[:2] != ["agent-security", "test"] or len(toks) < 3:
            fail("r5_run", f"{tid}: run line must start `agent-security test <harness>`")
            continue
        harness = toks[2]
        if harness not in harnesses:
            fail("r5_run", f"{tid}: harness {harness!r} is not registered in cli.py")
            continue
        hmod = root / harnesses[harness]
        if hmod.is_file() and hmod.resolve() != (root / mod).resolve():
            fail("r5_run", f"{tid}: harness {harness!r} runs {harnesses[harness]}, not {mod}")
        htext = hmod.read_text(encoding="utf-8") if hmod.is_file() else ""
        for flag in (x.split("=")[0] for x in toks if x.startswith("--")):
            if not re.search(r'add_argument\(\s*["\']' + re.escape(flag) + r'["\']', htext):
                fail("r5_flag", f"{tid}: {harnesses[harness]} defines no {flag} option")

    # r6: hand-written text stays factual.
    for where, text in _hand_fields(mapping):
        low = (text or "").lower()
        for phrase in PROHIBITED:
            if re.search(r"\b" + re.escape(phrase) + r"\b", low):
                fail("r6_language", f"{where} contains {phrase!r}")
    return fails


def validate_pinned(mapping: dict, root: Path = ROOT) -> list[str]:
    """Pinned rules. Caller must first establish the pinned commit is present."""
    fails: list[str] = []
    sha = mapping["pinned_commit"]
    if _git(root, "merge-base", "--is-ancestor", sha, "HEAD").returncode != 0:
        fails.append(f"[pin_ancestor] {sha[:12]} is not an ancestor of HEAD; "
                     "permalinks into it would not describe this branch's history")
    for tid, t in (mapping.get("tests") or {}).items():
        blob = pinned_blob(root, sha, t["module"])
        if blob is None:
            fails.append(f"[pin_module] {tid}: {t['module']} does not exist at {sha[:12]}")
            continue
        text = blob.decode("utf-8", errors="replace")
        if def_line(text, t["symbol"]) is None:
            fails.append(f"[pin_symbol] {tid}: def {t['symbol']} not at {sha[:12]}")
        for q in t.get("cites") or []:
            if locate(text, q) is None:
                fails.append(f"[pin_quote] {tid}: cited text not verbatim in {t['module']} "
                             f"at {sha[:12]}: {q[:70]!r}")
        for v in t.get("verdicts") or []:
            if not v.get("quote"):
                continue
            vmod = v.get("module", t["module"])
            vblob = pinned_blob(root, sha, vmod)
            vtext = vblob.decode("utf-8", errors="replace") if vblob is not None else ""
            if locate(vtext, v["quote"]) is None:
                fails.append(f"[pin_quote] {tid} {v['outcome']}: not verbatim in {vmod} at "
                             f"{sha[:12]}: {v['quote'][:70]!r}")
    return fails


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

def _permalink(mapping: dict, rel: str, line: int | None = None) -> str:
    url = f"{mapping['repository']}/blob/{mapping['pinned_commit']}/{rel}"
    return f"{url}#L{line}" if line else url


def _src_ref(mapping: dict, rel: str, line: int | None) -> str:
    label = f"{rel}:{line}" if line else rel
    return f"[`{label}`]({_permalink(mapping, rel, line)})"


def _quote_block(text: str) -> str:
    return "> " + _norm(text)


def _title(cve: str, c: dict) -> str:
    ids = ", ".join(d["test_id"] for d in c["documented"])
    return f"Testing for {cve} ({c['product']}): {ids}"


def render_cve(mapping: dict, cve: str, root: Path, catalog: dict[str, str]) -> str:
    c = mapping["cves"][cve]
    sha = mapping["pinned_commit"]
    short = sha[:7]
    date = mapping["retrieved"]
    src = mapping["sources"]
    out: list[str] = [GENERATED_BANNER, "", f"# {_title(cve, c)}", ""]
    out += [f"Source citations below are pinned to commit [`{short}`]"
            f"({mapping['repository']}/tree/{sha}). Vulnerability facts were retrieved "
            f"from the primary sources listed at the end on {date}. "
            "[All CVE pages](README.md).", ""]

    out += ["## The vulnerability", ""]
    out += [_quote_block(c["summary"]), ""]
    lead = "Excerpt from" if c["summary_is_excerpt"] else "From"
    out += [f"{lead} the {c['summary_source']} description of {cve}"
            f" ({src['nvd_page']}{cve}), retrieved {date}.", ""]
    out += ["| Field | Value | Source |", "|---|---|---|"]
    out.append(f"| Product | {c['product']} ({c['component']}) | NVD |")
    out.append(f"| Published | {c['published']} | NVD |")
    out.append(f"| NVD status | {c['nvd_status']} | NVD |")
    out.append(f"| Assigning CNA | {c['cna']} | NVD |")
    for a in c["affected"]:
        out.append(f"| Affected | {a['value']} | {a['source']} |")
    for f in c["fixed"]:
        out.append(f"| Fixed | {f['value']} | {f['source']} |")
    for v in c["cvss"]:
        out.append(f"| CVSS | {v['score']} {v['severity']} (CVSS {v['version']}, "
                   f"`{v['vector']}`) | {v['source']}, scored by {v['scored_by']} |")
    for w in c["cwe"]:
        out.append(f"| CWE | {w['id']} | {w['source']}, from {w['scored_by']} |")
    kev = c.get("kev")
    if kev:
        out.append(f"| CISA KEV | Listed. dateAdded {kev['date_added']}, dueDate "
                   f"{kev['due_date']}, knownRansomwareCampaignUse "
                   f"{kev['known_ransomware_campaign_use']} | CISA KEV catalog "
                   f"{mapping['kev_catalog_version']} |")
    else:
        out.append(f"| CISA KEV | Not listed in catalog version "
                   f"{mapping['kev_catalog_version']} as of {date} | CISA KEV catalog |")
    g = c.get("ghsa")
    if g:
        state = "reviewed" if g["reviewed"] else "unreviewed"
        out.append(f"| GitHub advisory | [{g['id']}](https://github.com/advisories/{g['id']})"
                   f" ({state}) | GitHub Advisory Database |")
    else:
        out.append(f"| GitHub advisory | {c['ghsa_note']} | GitHub Advisory Database |")
    out.append("")

    out += ["## ASH tests that exercise this class", ""]
    for d in c["documented"]:
        tid = d["test_id"]
        t = mapping["tests"][tid]
        text = pinned_blob(root, sha, t["module"]).decode("utf-8", errors="replace")
        dl = def_line(text, t["symbol"])
        where = "the target" if t["observes"] == "target" else \
            "the machine running the harness, not the target"
        out += [f"### {tid}: {catalog.get(tid, '')}", ""]
        out += [f"Defined at {_src_ref(mapping, t['module'], dl)} (`{t['symbol']}`). "
                f"Observes {where}.", ""]
        out += [d["why"], ""]
        out += ["The test's own source:", ""]
        for q in t["cites"]:
            ql = locate_in(text, q, t["symbol"])
            out += [_quote_block(q), ">", f"> {_src_ref(mapping, t['module'], ql)}", ""]
        out += [f"**What it sends.** {t['sends']}", ""]
        out += ["**Run it** against a target you are authorised to test:", "", "```sh",
                t["run"], "```", ""]
        out += ["**Verdicts.**", ""]
        for v in t["verdicts"]:
            line = f"- **{v['outcome']}**: {v['when']}"
            if v.get("quote"):
                vmod = v.get("module", t["module"])
                vtext = pinned_blob(root, sha, vmod).decode("utf-8", errors="replace")
                sym = t["symbol"] if vmod == t["module"] else None
                line += f" Source: {_src_ref(mapping, vmod, locate_in(vtext, v['quote'], sym))}"
                out += [line, f"  > {_norm(v['quote'])}"]
            else:
                out.append(line)
        out.append("")
        if t.get("notes"):
            out += ["**Read before relying on a verdict.**", ""]
            out += [f"- {n}" for n in t["notes"]]
            out.append("")

    if c.get("withheld"):
        out += ["## Tests the source pairs with this CVE that are not documented here", ""]
        for w in c["withheld"]:
            out.append(f"- **{w['test_id']}** ({catalog.get(w['test_id'], '')}): {w['reason']}")
        out.append("")

    out += ["## Scope", "",
            "These tests exercise the vulnerability class against a target you are "
            "authorised to test. They are not an exploit for the vendor product, they "
            "do not check the product's version, and a result does not establish that a "
            "given deployment is or is not affected by this CVE. What each outcome means "
            "in general is fixed in [RESULT-SEMANTICS.md](../RESULT-SEMANTICS.md).", ""]

    out += ["## Sources", "", f"All retrieved {date}.", ""]
    out.append(f"- NVD: {src['nvd_page']}{cve} (API: {src['nvd_api']}{cve})")
    if g:
        out.append(f"- GitHub Advisory Database: https://github.com/advisories/{g['id']} "
                   f"(API: {src['ghsa_api']}{cve})")
    else:
        out.append(f"- GitHub Advisory Database query: {src['ghsa_api']}{cve} (no result)")
    out.append(f"- CISA Known Exploited Vulnerabilities catalog, version "
               f"{mapping['kev_catalog_version']}: {src['kev_feed']}")
    for r in c.get("references") or []:
        out.append(f"- {r}")
    out.append("")
    return "\n".join(out)


def render_index(mapping: dict, root: Path, catalog: dict[str, str]) -> str:
    sha = mapping["pinned_commit"]
    date = mapping["retrieved"]
    cves = mapping["cves"]
    out = [GENERATED_BANNER, "", "# CVE to ASH test index", ""]
    out += ["Publicly disclosed CVEs that the harness source cites, and the tests that "
            "exercise each one's vulnerability class. Each page has the vulnerability "
            "facts from primary sources, the test's own source lines, the command to run "
            "it, and what each verdict means.", ""]
    out += ["A test here checks a vulnerability class against a target you are "
            "authorised to test. It is not a vendor exploit and a result does not "
            "establish that a deployment is or is not affected.", ""]
    out += ["| | |", "|---|---|",
            f"| Repository | `{mapping['repository']}` |",
            f"| Revision all citations are pinned to | `{sha}` |",
            f"| Vulnerability facts retrieved | {date} (NVD, GitHub Advisory Database, "
            f"CISA KEV catalog {mapping['kev_catalog_version']}) |",
            "| Generated by | `scripts/generate_cve_pages.py` from "
            "[`cve-test-mapping.yaml`](cve-test-mapping.yaml) |", ""]
    modules = sorted({t["module"] for t in mapping["tests"].values()})
    out += ["SHA-256 of the files cited, at that revision:", "", "```"]
    for rel in modules:
        out.append(f"{hashlib.sha256(pinned_blob(root, sha, rel)).hexdigest()}  {rel}")
    out += ["```", ""]

    out += ["## Documented", ""]
    out += ["| CVE | Product | ASH tests | CVSS (source) | CISA KEV |", "|---|---|---|---|---|"]
    for cve in sorted(cves, key=_cve_key):
        c = cves[cve]
        ids = ", ".join(d["test_id"] for d in c["documented"])
        cv = "; ".join(f"{v['score']} {v['severity']}, CVSS {v['version']}, {v['scored_by']}"
                       for v in c["cvss"])
        kev = f"Listed {c['kev']['date_added']}" if c.get("kev") else "Not listed"
        out.append(f"| [{cve}]({cve}.md) | {c['product']} | {ids} | {cv} | {kev} |")
    out.append("")

    withheld = [(cve, w) for cve in sorted(cves, key=_cve_key)
                for w in cves[cve].get("withheld") or []]
    if withheld:
        out += ["## Tests cited beside a documented CVE but not documented for it", ""]
        out += ["| CVE | Test | Reason |", "|---|---|---|"]
        for cve, w in withheld:
            out.append(f"| {cve} | {w['test_id']} | {w['reason']} |")
        out.append("")

    out += ["## CVEs cited in the source without a page", ""]
    out += ["| CVE | Reason |", "|---|---|"]
    for cve in sorted(mapping.get("excluded") or {}, key=_cve_key):
        out.append(f"| {cve} | {mapping['excluded'][cve]['reason']} |")
    out.append("")

    out += ["## How this list is kept honest", "",
            "The CVEs and their test pairings are derived from `protocol_tests/`, not "
            "written by hand. `python scripts/generate_cve_pages.py --check`, run by "
            "`testing/test_cve_pages_are_current.py`, fails when the source cites a CVE "
            "the mapping does not account for, when a test paired with a CVE in source "
            "is neither documented nor withheld with a reason, when a test ID does not "
            "exist or is missing from [HARNESS_TEST_CATALOG.md](../../HARNESS_TEST_CATALOG.md), "
            "when a quoted source line is not verbatim at the pinned revision, or when "
            "these pages differ from regenerated output.", "",
            "Vulnerability facts cannot be derived from this repository. They were "
            "retrieved from the sources named on each page and are re-retrieved, not "
            "edited, when updated.", ""]
    return "\n".join(out)


def _cve_key(cve: str) -> tuple[int, int]:
    _, year, num = cve.split("-")
    return int(year), int(num)


def render_all(mapping: dict, root: Path = ROOT) -> dict[Path, str]:
    catalog = catalog_entries(root)
    out = out_dir(root)
    pages = {out / "README.md": render_index(mapping, root, catalog)}
    for cve in mapping["cves"]:
        pages[out / f"{cve}.md"] = render_cve(mapping, cve, root, catalog)
    return pages


def drift(mapping: dict, root: Path = ROOT) -> list[str]:
    fails = []
    expected = render_all(mapping, root)
    for path, text in expected.items():
        rel = path.relative_to(root)
        if not path.is_file():
            fails.append(f"[drift] {rel} is missing; run scripts/generate_cve_pages.py")
        elif path.read_text(encoding="utf-8") != text:
            fails.append(f"[drift] {rel} differs from freshly generated output")
    for path in out_dir(root).glob("CVE-*.md"):
        if path not in expected:
            fails.append(f"[drift] {path.relative_to(root)} has no entry in the mapping")
    return fails


def load(root: Path = ROOT) -> dict:
    return yaml.safe_load(mapping_path(root).read_text(encoding="utf-8"))


def _require_checkout(root: Path) -> None:
    """One line naming the missing checkout resource, exit 2, no traceback."""
    for rel in ("/".join(MAPPING_PARTS), "HARNESS_TEST_CATALOG.md", "protocol_tests/cli.py",
                ".git"):
        if not (root / rel).exists():
            print(f"generate_cve_pages.py: checkout-only resource missing: {rel} (expected "
                  f"under {root}). This generator reads the CVE mapping, the test catalog "
                  "and git history, which the wheel does not ship; run it from a clone.",
                  file=sys.stderr)
            raise SystemExit(2)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="validate and compare with the pages on disk; write nothing")
    args = ap.parse_args(argv)
    _require_checkout(ROOT)
    mapping = load()
    fails = validate(mapping)
    sha = mapping.get("pinned_commit", "")
    pinned_ok = pin_available(ROOT, sha)
    if not pinned_ok and not is_shallow(ROOT):
        fails.append(f"[pin_missing] pinned_commit {sha[:12]} is not in this repository")
    if pinned_ok:
        fails += validate_pinned(mapping)
    if fails:
        print(f"FAIL - {len(fails)} rule violation(s):\n")
        for f in fails:
            print(f"  {f}")
        return 1
    if not pinned_ok:
        # Exit 2, the repository's "could not check" code: the HEAD rules held,
        # but a green exit here would read as the pages having been verified.
        print("HEAD rules pass. Pinned rules NOT RUN: shallow clone, pinned commit absent. "
              "Not a pass for the pages; run with full history.")
        return 2
    if args.check:
        d = drift(mapping)
        if d:
            print(f"FAIL - {len(d)} page(s) drifted:\n")
            for f in d:
                print(f"  {f}")
            return 1
        print(f"PASS - {len(mapping['cves'])} CVE pages, {len(mapping['excluded'])} "
              "excluded, all rules hold.")
        return 0
    for path, text in render_all(mapping).items():
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
